messages:
  prefix: "&9OpenFarming> &7"

  b_yes: "Yes"
  b_no: "No"

  types:
    crop: "Crop"
    animal: "Livestock"
    all: "Multi Function"

  locked: "{OPENFARMING-PREFIX}&cYou can't interact with this farm as you don't own it."
  broken: "{OPENFARMING-PREFIX}Farm broken."
  placed: "{OPENFARMING-PREFIX}Farm placed."

  insufficient_funds: "{OPENFARMING-PREFIX}&cInsufficient Funds."

item:
  title: "&eAutomated &9&l{FARM-TYPE} &r&eFarm"

upgrades:
  radius:
    enabled: true
    purchased: "{OPENFARMING-PREFIX}Radius upgraded to &f{VALUE} &7blocks."
    levels:
      0: # DEFAULT LEVEL
        value: 4
      1:
        value: 5
        ecoCost: 100
        expCost: 100
      2:
        value: 6
        ecoCost: 200
        expCost: false
      3:
        value: 7
        ecoCost: 300
        expCost: false

    gui:
      material: COMPASS
      purchasable:
        name: "&eUpgrade Radius to &f{NEXTVALUE} &eblocks."
        lore:
          - ""
          - "&fLeft click &eto upgrade for &f${ECO}"
          - "&fRight click &eto upgrade for &f{EXP} &eEXP"
      max:
        name: "&eRadius &f{VALUE} &eblocks &8(&aMAX&8)"
        lore: false

  speed:
    enabled: true
    purchased: "{OPENFARMING-PREFIX}Speed upgraded to &f{VALUE}x&7."
    levels:
      0: # DEFAULT LEVEL
        value: 1
      1:
        value: 1.25
        ecoCost: 100
        expCost: 0
      2:
        value: 1.5
        ecoCost: 200
        expCost: 0
      3:
        value: 1.75
        ecoCost: 300
        expCost: 0
      4:
        value: 2
        ecoCost: 400
        expCost: 0
    gui:
      material: SUGAR
      purchasable:
        name: "&eUpgrade Speed to &f{NEXTVALUE}x"
        lore:
          - ""
          - "&fLeft click &eto upgrade for &f${ECO}"
          - "&fRight click &eto upgrade for &f{EXP} &eEXP"
      max:
        name: "&eSpeed &f{VALUE}x &8(&aMAX&8)"
        lore: false

  autoReplant:
    enabled: true
    purchased: "{OPENFARMING-PREFIX}&fAuto Replant &7upgrade purchased."
    ecoCost: 1000
    expCost: 20000

    gui:
      material: SUNFLOWER
      locked:
        name: "&eAuto Replant"
        lore:
          - ""
          - "&7Automatically replants crops."
          - ""
          - "&fLeft click &eto purchase for &f${ECO}"
          - "&fRight click &eto purchase for &f{EXP} &eEXP"
      unlocked:
        name: "&eAuto Replant &8(&aPurchased&8)"
        lore: false

gui:
  title: "&0Farm Overview"
  previous:
    title: "&ePrevious Page"
  next:
    title: "&eNext Page"

  overview:
    title: "&eAutomated &f&l{TYPE} &r&eFarm"

    lore:
      - ""
      - "&eRadius: &f{RADIUS} Blocks"
      - "&eSpeed: &f{SPEED}x"
      - "&eAuto Replant: &f{REPLANT}"
      - ""