name: OpenFarming
version: @version@
main: io.github.openspigot.openfarming.OpenFarming
api-version: 1.13
authors: [LegendEffects]
website: openspigot.github.io

commands:
  openfarming:
    description: Main OpenFarming Command
    usage: /<command>